#!/bin/bash

echo "========================================"
echo "Guía para conectar con clientes SFTP"
echo "========================================"
echo ""
echo "1. LÍNEA DE COMANDOS (sftp):"
echo "   sftp -P 2222 sftpuser@localhost"
echo "   Contraseña: sftppass123"
echo ""
echo "2. FILEZILLA (Cliente gráfico):"
echo "   Host: sftp://localhost"
echo "   Puerto: 2222"
echo "   Usuario: sftpuser"
echo "   Contraseña: sftppass123"
echo ""
echo "3. PYTHO:"
echo "   Ver ejemplo en: app/example_manual_upload.py"
echo ""
echo "4. SUBIR ARCHIVO DESDE HOST:"
echo "   Crea un archivo en tu máquina local:"
echo "   echo 'Hola Mundo' > /tmp/mi_archivo.txt"
echo ""
echo "   Luego conéctate y súbelo:"
echo "   sftp -P 2222 sftpuser@localhost << EOF"
echo "   put /tmp/mi_archivo.txt /upload/mi_archivo.txt"
echo "   ls /upload"
echo "   bye"
echo "   EOF"
echo ""
echo "5. ARCHIVOS SUBIDOS SE GUARDAN EN:"
echo "   ./sftp_data/ host
echo ""
echo "=========================================="
